name: kf_drawer
description: Side menu (Drawer)
version: 1.3.3
homepage: https://github.com/qqmikey/kf_drawer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

